### ISSUE TITLE
How often do map tiles need to be updated

### ISSUE THREAD

**Issue by Ghostyfied** [fffam/blackdesert-somethinglovely-map#1]
Title!!! 
And is someone else already picking this up?

**Comment by fffam** [comment]
> How often do map tiles need to be updated

The map tiles have to be updated whenever the game changes the map significantly; Normally this is when new areas are added to the game, or when changes are made to existing areas. On average it was about twice/three times a year. Updating from the KR version after it patches (but before they land on NAEU) is ideal but not necessary.

> And is someone else already picking this up?

A few people have messaged on Discord (fffam) and made some progress with it, but I don't believe any of them have yet created a new set of map tiles.

**Comment by fffam** [comment]
Closing issue due to question answered. Continue to use this issue for discussion.
